all: nit noise
nit: make1 make2 make3 make4 make5 make6 makea e1.txt e2.txt ea.txt

make1: make1.gp
	gnuplot make1.gp
make2: make2.gp
	gnuplot make2.gp
make3: make3.gp
	gnuplot make3.gp
make4: make4.gp
	gnuplot make4.gp
make5: make5.gp
	gnuplot make5.gp
make6: make6.gp
	gnuplot make6.gp
makea: makea.gp
	gnuplot makea.gp

noise: makea1 makea2 makea3 makea4 makea5 makea6

makea1: makea1.gp
	gnuplot makea1.gp
makea2: makea2.gp
	gnuplot makea2.gp
makea3: makea3.gp
	gnuplot makea3.gp
makea4: makea4.gp
	gnuplot makea4.gp
makea5: makea5.gp
	gnuplot makea5.gp
makea6: makea6.gp
	gnuplot makea6.gp

clean:
	rm *.aux *.log *~