all:	qc_main.tex
	pdflatex qc_main.tex
	pdflatex qc_main.tex
	bibtex qc_main
	pdflatex qc_main.tex

clean:
	rm *.ps
	rm *.pdf
	rm *.nav 
	rm *.out 
	rm *.aux 
	rm *.bbl
	rm *.blg
	rm *.dvi
	rm *.log
	rm *.snm
	rm *.toc
	rm *.backup
	rm *~